name: MyFirstCI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      log_name:
        description: "Optional log filename"
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/hello.sh

      - name: Run the Bash script
        run: |
          LOG_NAME="${{ github.event.inputs.log_name }}"
          if [ -n "$LOG_NAME" ]; then
            ./scripts/hello.sh "$LOG_NAME"
          else
            ./scripts/hello.sh
          fi

      - name: Verify log file created
        run: |
          LOGFILE=$(ls -t logs/log-*.txt | head -n 1)
          echo "Last log: $LOGFILE"
          grep "Hello from Bash!" "$LOGFILE"
          grep "Date_time:" "$LOGFILE"
          grep -E "File count: [0-9]+" "$LOGFILE"

      - name: Verify history log updated
        run: |
          echo "Checking logs/history.txt..."
          tail -n 5 logs/history.txt
          grep "$(basename $LATEST_LOG)" logs/history.txt

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-log
          path: logs/log-*.txt
